# This workflow will build winpe then publish a package to GitHub Packages when a release is created
# 
name: Create WinPE_amd64.iso
# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #  branches: [ master ]
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Choco
        shell: pwsh
        run: |
          if(test-path -path "$env:ALLUSERSPROFILE\chocolatey\choco.exe"){Write-Output "Choco is already installed"} else {
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }
      - name: Install ADK
        shell: pwsh
        run: choco install windows-adk-all  -y # https://go.microsoft.com/fwlink/?linkid=2165884
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the WinPE image
        shell: pwsh
        run: .\New-WinPEImage.ps1
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WinPE_amd64.iso
          path: .\WinPE_amd64.iso
          if-no-files-found: error     
